/*
================================================================================
WAREHOUSE MANAGEMENT - ANALYTICAL QUERIES
SQL Server / SSMS
20 business questions with answer queries, based on the WarehouseManagement DB
(Suppliers, Products, Warehouses, Inventory, Customers, Orders, OrderDetails)
================================================================================
*/

USE WarehouseManagement;
GO

/*==============================================================================
SECTION 1 - PRODUCTS, SUPPLIERS & CATEGORIES
==============================================================================*/

/* 1. List all products with their category, price, and supplier name */
SELECT
    p.ProductID,
    p.ProductName,
    p.Category,
    p.UnitPrice,
    s.SupplierName
FROM Products p
JOIN Suppliers s
    ON p.SupplierID = s.SupplierID
ORDER BY p.Category, p.ProductName;

/* 2. How many products does each supplier provide? */
SELECT
    s.SupplierName,
    COUNT(p.ProductID) AS ProductCount
FROM Suppliers s
JOIN Products p
    ON s.SupplierID = p.SupplierID
GROUP BY s.SupplierName
ORDER BY ProductCount DESC;

/* 3. What is the average unit price per category? */
SELECT
    Category,
    COUNT(*) AS ProductCount,
    AVG(UnitPrice) AS AvgPrice,
    MIN(UnitPrice) AS MinPrice,
    MAX(UnitPrice) AS MaxPrice
FROM Products
GROUP BY Category
ORDER BY AvgPrice DESC;

/* 4. Which suppliers generate the highest total revenue through their products? */
SELECT TOP (5)
    s.SupplierName,
    SUM(od.Quantity * od.UnitPrice) AS TotalRevenue
FROM Suppliers s
JOIN Products p
    ON s.SupplierID = p.SupplierID
JOIN OrderDetails od
    ON p.ProductID = od.ProductID
GROUP BY s.SupplierName
ORDER BY TotalRevenue DESC;

/*==============================================================================
SECTION 2 - INVENTORY & WAREHOUSES
==============================================================================*/

/* 5. What is the total quantity in stock for each product across all warehouses? */
SELECT
    p.ProductName,
    SUM(i.Quantity) AS TotalStock
FROM Inventory i
JOIN Products p
    ON i.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalStock DESC;

/* 6. Which products are below their reorder level (need restocking), and in which warehouse? */
SELECT
    w.WarehouseName,
    p.ProductName,
    i.Quantity,
    i.ReorderLevel,
    (i.ReorderLevel - i.Quantity) AS UnitsBelowReorder
FROM Inventory i
JOIN Products p
    ON i.ProductID = p.ProductID
JOIN Warehouses w
    ON i.WarehouseID = w.WarehouseID
WHERE i.Quantity <= i.ReorderLevel
ORDER BY UnitsBelowReorder DESC;

/* 7. What is the total inventory value (Quantity * UnitPrice) per warehouse? */
SELECT
    w.WarehouseName,
    SUM(i.Quantity * p.UnitPrice) AS InventoryValue
FROM Inventory i
JOIN Warehouses w
    ON i.WarehouseID = w.WarehouseID
JOIN Products p
    ON i.ProductID = p.ProductID
GROUP BY w.WarehouseName
ORDER BY InventoryValue DESC;

/* 8. What percentage of each warehouse's capacity is currently used (by unit count)? */
SELECT
    w.WarehouseName,
    w.Capacity,
    SUM(i.Quantity) AS UnitsStored,
    CAST(100.0 * SUM(i.Quantity) / w.Capacity AS DECIMAL(6,2)) AS CapacityUsedPct
FROM Warehouses w
JOIN Inventory i
    ON w.WarehouseID = i.WarehouseID
GROUP BY w.WarehouseName, w.Capacity
ORDER BY CapacityUsedPct DESC;

/* 9. Stock health report: flag every warehouse/product row as Low Stock or OK */
SELECT
    w.WarehouseName,
    p.ProductName,
    i.Quantity,
    i.ReorderLevel,
    CASE
        WHEN i.Quantity <= i.ReorderLevel THEN 'Low Stock'
        ELSE 'OK'
    END AS StockStatus
FROM Inventory i
JOIN Warehouses w ON i.WarehouseID = w.WarehouseID
JOIN Products p ON i.ProductID = p.ProductID
ORDER BY StockStatus, w.WarehouseName;

/* 10. Which products exist in more than 3 warehouses? (wide distribution) */
SELECT
    p.ProductName,
    COUNT(DISTINCT i.WarehouseID) AS WarehousesStockedIn
FROM Inventory i
JOIN Products p
    ON i.ProductID = p.ProductID
GROUP BY p.ProductName
HAVING COUNT(DISTINCT i.WarehouseID) > 3
ORDER BY WarehousesStockedIn DESC;

/*==============================================================================
SECTION 3 - CUSTOMERS & ORDERS
==============================================================================*/

/* 11. What is the total revenue generated by each customer? */
SELECT
    c.CustomerName,
    SUM(od.Quantity * od.UnitPrice) AS TotalSpent
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
GROUP BY c.CustomerName
ORDER BY TotalSpent DESC;

/* 12. Who are the top 5 customers by total spending? */
SELECT TOP (5)
    c.CustomerName,
    SUM(od.Quantity * od.UnitPrice) AS TotalSpent
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
GROUP BY c.CustomerName
ORDER BY TotalSpent DESC;

/* 13. Which customers placed more than one order? */
SELECT
    c.CustomerName,
    COUNT(o.OrderID) AS OrderCount
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerName
HAVING COUNT(o.OrderID) > 1
ORDER BY OrderCount DESC;

/* 14. What is the value of each order (quantity * price, summed per order)? */
SELECT
    o.OrderID,
    c.CustomerName,
    o.OrderDate,
    o.Status,
    SUM(od.Quantity * od.UnitPrice) AS OrderValue
FROM Orders o
JOIN Customers c
    ON o.CustomerID = c.CustomerID
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
GROUP BY o.OrderID, c.CustomerName, o.OrderDate, o.Status
ORDER BY OrderValue DESC;

/* 15. What is the average order value across the whole company? */
SELECT
    AVG(OrderTotal) AS AvgOrderValue
FROM
(
    SELECT
        o.OrderID,
        SUM(od.Quantity * od.UnitPrice) AS OrderTotal
    FROM Orders o
    JOIN OrderDetails od
        ON o.OrderID = od.OrderID
    GROUP BY o.OrderID
) AS OrderTotals;

/* 16. Which orders are above the average order value? */
SELECT
    o.OrderID,
    c.CustomerName,
    SUM(od.Quantity * od.UnitPrice) AS OrderValue
FROM Orders o
JOIN Customers c
    ON o.CustomerID = c.CustomerID
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
GROUP BY o.OrderID, c.CustomerName
HAVING SUM(od.Quantity * od.UnitPrice) >
(
    SELECT AVG(OrderTotal)
    FROM
    (
        SELECT SUM(Quantity * UnitPrice) AS OrderTotal
        FROM OrderDetails
        GROUP BY OrderID
    ) AS t
)
ORDER BY OrderValue DESC;

/* 17. What is the order status breakdown (count and % of total orders)? */
SELECT
    Status,
    COUNT(*) AS OrderCount,
    CAST(100.0 * COUNT(*) / (SELECT COUNT(*) FROM Orders) AS DECIMAL(6,2)) AS PctOfOrders
FROM Orders
GROUP BY Status
ORDER BY OrderCount DESC;

/*==============================================================================
SECTION 4 - REVENUE ANALYSIS (CTE + WINDOW FUNCTIONS)
==============================================================================*/

/* 18. What is the monthly revenue trend? */
SELECT
    FORMAT(o.OrderDate, 'yyyy-MM') AS OrderMonth,
    SUM(od.Quantity * od.UnitPrice) AS MonthlyRevenue
FROM Orders o
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
GROUP BY FORMAT(o.OrderDate, 'yyyy-MM')
ORDER BY OrderMonth;

/* 19. What is the running total of revenue month over month? */
WITH MonthlyRevenue AS
(
    SELECT
        CAST(FORMAT(o.OrderDate, 'yyyy-MM') AS VARCHAR(7)) AS OrderMonth,
        SUM(od.Quantity * od.UnitPrice) AS Revenue
    FROM Orders o
    JOIN OrderDetails od
        ON o.OrderID = od.OrderID
    GROUP BY FORMAT(o.OrderDate, 'yyyy-MM')
)
SELECT
    OrderMonth,
    Revenue,
    SUM(Revenue) OVER (ORDER BY OrderMonth) AS RunningTotalRevenue
FROM MonthlyRevenue
ORDER BY OrderMonth;
/* 20. Rank products by total revenue within their own category */
WITH ProductRevenue AS
(
    SELECT
        p.Category,
        p.ProductName,
        SUM(od.Quantity * od.UnitPrice) AS TotalRevenue
    FROM Products p
    JOIN OrderDetails od
        ON p.ProductID = od.ProductID
    GROUP BY p.Category, p.ProductName
)
SELECT
    Category,
    ProductName,
    TotalRevenue,
    RANK() OVER (PARTITION BY Category ORDER BY TotalRevenue DESC) AS RevenueRankInCategory
FROM ProductRevenue
ORDER BY Category, RevenueRankInCategory;


/* 21. DISTINCT - What cities do our customers come from? */
SELECT DISTINCT City
FROM Customers
ORDER BY City;

/* 22. LIKE - Which products have "Cable" or "Cord" in their name? */
SELECT ProductName, Category, UnitPrice
FROM Products
WHERE ProductName LIKE '%Cable%'
   OR ProductName LIKE '%Cord%';

/* 23. BETWEEN - Which orders were placed in Q2 2026 (April to June)? */
SELECT OrderID, CustomerID, OrderDate, Status
FROM Orders
WHERE OrderDate BETWEEN '2026-04-01' AND '2026-06-30'
ORDER BY OrderDate;

/* 24. How many orders has EVERY customer placed,
       including customers with zero orders? */
SELECT
    c.CustomerName,
    COUNT(o.OrderID) AS OrderCount
FROM Customers c
LEFT JOIN Orders o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerName
ORDER BY OrderCount ASC;

/* 25. Which products are priced above the
       average price of their own category? */
SELECT
    p.ProductName,
    p.Category,
    p.UnitPrice
FROM Products p
WHERE p.UnitPrice >
(
    SELECT AVG(p2.UnitPrice)
    FROM Products p2
    WHERE p2.Category = p.Category
)
ORDER BY p.Category, p.UnitPrice DESC;

/* 26. Rank customers by total spending
       and compare the three ranking styles side by side */
WITH CustomerSpend AS
(
    SELECT
        c.CustomerName,
        SUM(od.Quantity * od.UnitPrice) AS TotalSpent
    FROM Customers c
    JOIN Orders o ON c.CustomerID = o.CustomerID
    JOIN OrderDetails od ON o.OrderID = od.OrderID
    GROUP BY c.CustomerName
)
SELECT
    CustomerName,
    TotalSpent,
    ROW_NUMBER() OVER (ORDER BY TotalSpent DESC) AS RowNum,
    RANK()       OVER (ORDER BY TotalSpent DESC) AS RankNum,
    DENSE_RANK() OVER (ORDER BY TotalSpent DESC) AS DenseRankNum
FROM CustomerSpend
ORDER BY TotalSpent DESC;

/* 27. LAG - What was the change in revenue compared to the previous month? */
WITH MonthlyRevenue AS
(
    SELECT
        CAST(FORMAT(o.OrderDate, 'yyyy-MM') AS VARCHAR(7)) AS OrderMonth,
        SUM(od.Quantity * od.UnitPrice) AS Revenue
    FROM Orders o
    JOIN OrderDetails od ON o.OrderID = od.OrderID
    GROUP BY FORMAT(o.OrderDate, 'yyyy-MM')
)
SELECT
    OrderMonth,
    Revenue,
    LAG(Revenue) OVER (ORDER BY OrderMonth) AS PreviousMonthRevenue,
    Revenue - LAG(Revenue) OVER (ORDER BY OrderMonth) AS RevenueChange
FROM MonthlyRevenue
ORDER BY OrderMonth;

